import type { Stage, StageInfo, Topic } from "./types";

export const STAGES: Record<Stage, StageInfo> = {
  lagstadiet: {
    id: "lagstadiet",
    title: "Lågstadiet",
    subtitle: "Årskurs 1–3",
    grades: "1–3",
    description:
      "Lek dig till tal, addition, klockan och former. Här bygger du grunden!",
    accent: "amber",
  },
  mellanstadiet: {
    id: "mellanstadiet",
    title: "Mellanstadiet",
    subtitle: "Årskurs 4–6",
    grades: "4–6",
    description:
      "Multiplikation, bråk, decimaltal och geometri. Dags att utmana hjärnan!",
    accent: "sky",
  },
  hogstadiet: {
    id: "hogstadiet",
    title: "Högstadiet",
    subtitle: "Årskurs 7–9",
    grades: "7–9",
    description:
      "Algebra, ekvationer, Pythagoras och funktioner. Förbered dig för gymnasiet.",
    accent: "violet",
  },
};

export const STAGE_ORDER: Stage[] = ["lagstadiet", "mellanstadiet", "hogstadiet"];

export const TOPICS: Topic[] = [
  // ---------- Lågstadiet ----------
  {
    id: "talraknemastare",
    stage: "lagstadiet",
    title: "Talen 0–100",
    blurb: "Lär dig räkna, jämföra och placera tal på tallinjen.",
    emoji: "🔢",
    skill: "Naturliga tal och deras egenskaper",
    level: 1,
  },
  {
    id: "talkompisar",
    stage: "lagstadiet",
    title: "Talkompisar",
    blurb: "Hitta talen som tillsammans blir 10, 20 eller 100.",
    emoji: "🤝",
    skill: "Talkamrater och uppdelning av tal",
    level: 1,
  },
  {
    id: "addition-sub-100",
    stage: "lagstadiet",
    title: "Addition upp till 100",
    blurb: "Plussa ihop tal med och utan tiotalsövergång.",
    emoji: "➕",
    skill: "Räknemetoder för addition",
    level: 2,
  },
  {
    id: "subtraktion-sub-100",
    stage: "lagstadiet",
    title: "Subtraktion upp till 100",
    blurb: "Ta bort och räkna mellanrum mellan tal.",
    emoji: "➖",
    skill: "Räknemetoder för subtraktion",
    level: 2,
  },
  {
    id: "talmonster",
    stage: "lagstadiet",
    title: "Talmönster",
    blurb: "Hitta nästa tal i serien.",
    emoji: "🧩",
    skill: "Mönster i talföljder",
    level: 2,
  },
  {
    id: "klockan",
    stage: "lagstadiet",
    title: "Klockan",
    blurb: "Hela timmar, halvtimmar och kvart över/i.",
    emoji: "🕒",
    skill: "Tid och tidsuppfattning",
    level: 3,
  },
  {
    id: "former",
    stage: "lagstadiet",
    title: "Geometriska former",
    blurb: "Cirklar, trianglar, kvadrater och rektanglar.",
    emoji: "🔷",
    skill: "Grundläggande geometri",
    level: 1,
  },
  {
    id: "matning",
    stage: "lagstadiet",
    title: "Mäta och väga",
    blurb: "Centimeter, meter, gram och kilo.",
    emoji: "📏",
    skill: "Mätning av längd, vikt och volym",
    level: 3,
  },
  {
    id: "halvor-och-delar",
    stage: "lagstadiet",
    title: "Halvor och delar",
    blurb: "Dela upp i lika stora delar — enkla bråk.",
    emoji: "🍕",
    skill: "Del av helhet, enkla bråk",
    level: 4,
  },
  {
    id: "tredim-former",
    stage: "lagstadiet",
    title: "3D-former",
    blurb: "Klot, kon, cylinder och rätblock.",
    emoji: "🧊",
    skill: "Tredimensionella objekt",
    level: 2,
  },
  {
    id: "symmetri",
    stage: "lagstadiet",
    title: "Symmetri",
    blurb: "Vilka former har en symmetrilinje?",
    emoji: "🦋",
    skill: "Symmetri i bilder och former",
    level: 3,
  },
  {
    id: "diagram",
    stage: "lagstadiet",
    title: "Tabeller och diagram",
    blurb: "Läs av enkla diagram och tabeller.",
    emoji: "📊",
    skill: "Enkla tabeller och diagram",
    level: 3,
  },

  // ---------- Mellanstadiet ----------
  {
    id: "multiplikationstabellen",
    stage: "mellanstadiet",
    title: "Multiplikationstabellen",
    blurb: "Träna 1–10:ans tabell tills du knäcker den.",
    emoji: "✖️",
    skill: "Multiplikation, automatiserad",
    level: 1,
  },
  {
    id: "division",
    stage: "mellanstadiet",
    title: "Division",
    blurb: "Dela tal jämnt och med rest.",
    emoji: "➗",
    skill: "Division och samband med multiplikation",
    level: 2,
  },
  {
    id: "stora-tal",
    stage: "mellanstadiet",
    title: "Stora tal",
    blurb: "Tusental, tiotusental och positionssystemet.",
    emoji: "💯",
    skill: "Positionssystemet",
    level: 2,
  },
  {
    id: "decimaltal",
    stage: "mellanstadiet",
    title: "Decimaltal",
    blurb: "Räkna med tal som har decimaler.",
    emoji: "🔟",
    skill: "Decimaltal och deras egenskaper",
    level: 3,
  },
  {
    id: "brak",
    stage: "mellanstadiet",
    title: "Bråk",
    blurb: "Liknämniga bråk, addera och förkorta.",
    emoji: "🍰",
    skill: "Bråk, del av helhet och antal",
    level: 3,
  },
  {
    id: "procent",
    stage: "mellanstadiet",
    title: "Procent",
    blurb: "Procent som del av hundra.",
    emoji: "％",
    skill: "Procent och samband med bråk",
    level: 4,
  },
  {
    id: "geometri-area",
    stage: "mellanstadiet",
    title: "Omkrets och area",
    blurb: "Beräkna för rektanglar och kvadrater.",
    emoji: "📐",
    skill: "Geometri – omkrets och area",
    level: 4,
  },
  {
    id: "tid-och-enheter",
    stage: "mellanstadiet",
    title: "Tid och enheter",
    blurb: "Omvandla mellan enheter och räkna tid.",
    emoji: "⏱️",
    skill: "Enhetsbyten",
    level: 3,
  },
  {
    id: "statistik",
    stage: "mellanstadiet",
    title: "Medelvärde & diagram",
    blurb: "Tolka data, räkna medelvärde, median.",
    emoji: "📊",
    skill: "Lägesmått och tolkning av data",
    level: 4,
  },
  {
    id: "negativa-tal",
    stage: "mellanstadiet",
    title: "Negativa tal",
    blurb: "Tal under noll — termometer-tänk.",
    emoji: "🌡️",
    skill: "Rationella tal inklusive negativa tal",
    level: 3,
  },
  {
    id: "koordinatsystem",
    stage: "mellanstadiet",
    title: "Koordinatsystem",
    blurb: "Hitta punkter med x- och y-koordinater.",
    emoji: "📍",
    skill: "Koordinatsystem",
    level: 3,
  },
  {
    id: "vinklar",
    stage: "mellanstadiet",
    title: "Vinklar",
    blurb: "Räta, spetsiga och trubbiga vinklar.",
    emoji: "📐",
    skill: "Vinkelmått",
    level: 3,
  },

  // ---------- Högstadiet ----------
  {
    id: "algebra-uttryck",
    stage: "hogstadiet",
    title: "Algebraiska uttryck",
    blurb: "Förenkla, expandera och sätt in värden.",
    emoji: "𝑥",
    skill: "Algebraiska uttryck",
    level: 1,
  },
  {
    id: "ekvationer",
    stage: "hogstadiet",
    title: "Ekvationer",
    blurb: "Lös linjära ekvationer steg för steg.",
    emoji: "⚖️",
    skill: "Linjära ekvationer",
    level: 2,
  },
  {
    id: "potenser",
    stage: "hogstadiet",
    title: "Potenser och rötter",
    blurb: "Kvadrater, kuber, kvadratrötter.",
    emoji: "²",
    skill: "Potenslagar och kvadratrötter",
    level: 3,
  },
  {
    id: "pythagoras",
    stage: "hogstadiet",
    title: "Pythagoras sats",
    blurb: "Beräkna sidor i rätvinkliga trianglar.",
    emoji: "📐",
    skill: "Pythagoras sats",
    level: 4,
  },
  {
    id: "funktioner",
    stage: "hogstadiet",
    title: "Funktioner",
    blurb: "Räta linjens ekvation och värdetabeller.",
    emoji: "📈",
    skill: "Linjära funktioner",
    level: 4,
  },
  {
    id: "procent-ranta",
    stage: "hogstadiet",
    title: "Procent och ränta",
    blurb: "Förändringar, ökning, minskning och ränta.",
    emoji: "💰",
    skill: "Procent, ränta och förändringsfaktor",
    level: 3,
  },
  {
    id: "sannolikhet",
    stage: "hogstadiet",
    title: "Sannolikhet",
    blurb: "Tärningar, mynt och enkla utfall.",
    emoji: "🎲",
    skill: "Sannolikhet och kombinatorik",
    level: 3,
  },
  {
    id: "geometri-volym",
    stage: "hogstadiet",
    title: "Volym och area",
    blurb: "Räkna volym på rätblock, cylindrar mm.",
    emoji: "📦",
    skill: "Geometri – volym, area",
    level: 4,
  },
  {
    id: "skala-och-proportion",
    stage: "hogstadiet",
    title: "Skala & proportion",
    blurb: "Kartor, ritningar och proportionella samband.",
    emoji: "🗺️",
    skill: "Skala och proportionalitet",
    level: 3,
  },
  {
    id: "cirkeln",
    stage: "hogstadiet",
    title: "Cirkeln",
    blurb: "Omkrets, area och pi.",
    emoji: "⭕",
    skill: "Cirkelns geometri",
    level: 3,
  },
  {
    id: "vetenskaplig-notation",
    stage: "hogstadiet",
    title: "Tiopotenser",
    blurb: "Skriv stora och små tal med 10-potenser.",
    emoji: "🔬",
    skill: "Potenser och grundpotensform",
    level: 4,
  },
  {
    id: "likformighet",
    stage: "hogstadiet",
    title: "Likformighet",
    blurb: "Skala mellan likformiga figurer.",
    emoji: "🔺",
    skill: "Likformighet och kongruens",
    level: 4,
  },
];

export const topicsForStage = (stage: Stage): Topic[] =>
  TOPICS.filter((t) => t.stage === stage);

export const getTopic = (id: string): Topic | undefined =>
  TOPICS.find((t) => t.id === id);
